# Generated by Django 4.0 on 2021-12-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_player_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='x_coord',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='move',
            name='y_coord',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='num_moves_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
